# SoRA: Video generation models as world simulators
#
# Configuration file for a SoRA-based text-to-video diffusion model. Since there
# is no official SoRA code or paper, this model is based on what little information
# we can glean from public sources. We use two
# Imagen Video
#
diffusion:
  parameterization: "v"
  # Sampling section determines the size of the sampled output
  # from the model, and defines the sampling method used
  sampling:
    output_channels: 1
    output_spatial_size: 32
    output_frames: 16
    target: xdiffusion.samplers.ancestral.AncestralSampler
    params: {}

  # The noise scheduler to use with the forward diffusion process.
  noise_scheduler:
    target: xdiffusion.scheduler.ContinuousNoiseScheduler
    params:
      num_scales: 1024
      logsnr_schedule: "cosine"
      loss_type: "l2"
      logsnr_min: -20
      logsnr_max: 20
  importance_sampler:
    target: xdiffusion.importance_sampling.UniformSampler
    params:
      num_timesteps: 1024
  # A preprocessor to use with the context before sending to the score network.
  context_preprocessing:
      # The Prompts Preprocessor converts the list of text prompts in the context
      # into a batch of text tokens of shape (B, text_context_size)
      - target: xdiffusion.layers.embedding.T5TextEmbedder
        params:
          # The max length of the text token sequence
          max_length: 128
          # The name of the T5 text model to use
          version: "google/t5-v1_1-base"
          context_key: "t5_text_embeddings"
  # A preprocessor for input to the model.
  input_preprocessing:
    target: xdiffusion.context.IgnoreInputPreprocessor
    params: {}
  # Setting for classifier free guidance.
  classifier_free_guidance:
    # Classifier-free guidance scale, where the value is >= 1.0
    classifier_free_guidance: 0.0
    # Unconditional guidance probability
    unconditional_guidance_probability: 0.0
    # The context signals to apply guidance to.
    signals: ["text_prompts"]
    # For classifier free guidance, we need the ability to create an unconditional
    # context given the conditional context. This unconditional context needs
    # to be applied in both training and sampling, and will return a new
    # context dictionary given the original context dictionary.
    unconditional_context:
      target: xdiffusion.context.UnconditionalTextPromptsAdapter
      params: {}
  dynamic_thresholding:
    enable: False
    p: 0.99
    c: 1.7
  # Defines the score network for predicting the noise parameter
  score_network:
    target: xdiffusion.score_networks.sora_v1.Sora
    params:
      input_spatial_size: 32
      # Model input channels
      input_channels: 1
      # Model input number of frames
      input_number_of_frames: 16
      # The image patch input dimensions (C*PH*PW)
      in_channels: 64
      # Vec is the CLIP text embedding dimension
      vec_in_dim: 768
      # The T5 text embedding dimension
      context_in_dim: 768
      # Spatial patch size
      spatial_patch_size: 8
      # The number of temporal dimensions (frames)
      num_temporal_tokens: 16
      # The number of spatial tokens. Is equal
      # to (input_spatial_size // spatial_patch_size)**2
      num_spatial_tokens: 16
      # The hidden size of the transformer blocks
      hidden_size: 384
      # MLP ratio (expands the hidden size) in transformer blocks
      mlp_ratio: 4.0
      # Number of attention heads
      num_heads: 6
      # Transformer depth
      depth: 12
      # Dimensions of ROPE axes. Must sum to in_channels.
      axes_dim: [16, 24, 24]
      theta: 10000
      qkv_bias: True
      guidance_embed: False
      is_learned_sigma: False
      is_class_conditional: False
      # Additional conditioning signals for the model. The projections
      # defined here will be applied before running through the rest of the
      # score network.
      conditioning:
        # The signals (keys in the dictionary) that are available in the conditioning
        # context.
        signals: []
        projections: {}
        # The context transformer to use at the top of the score network. This transforms
        # the context with a shared set of parameters.
        context_transformer_head:
          # Timestep -> timestep embedding
          - target: torch.nn.Identity
            params: {}
# Describes the dataset used in training.
data:
  # Spatial width/height of the data input to the model.
  image_size: 32
  # Number of channels in the input data
  num_channels: 1
  # The number of classes in the dataset
  num_classes: 10
  # The number of frames in the input dataset. This could be different
  # than the number of frames that is in the data itself.
  input_number_of_frames: 16
  # Method of processing the input frames. Can be "clip", which takes
  # the first N frames, or "sample", which skips frames from the input
  # to get the required number of frames (so a source video of 30 frames, with input_number_of_frames
  # set to 15, would take every (30//15=2) frames).
  frame_processing: "clip"