# Configuration for an audio autoencoder with a latent space of 4x16x32,
# which accepts input data of shape (1, 128, 256)
embed_dim: 4
loss_config:
  target: xdiffusion.autoencoders.contperceptual.LPAPSWithDiscriminator
  params:
    disc_start: 50001
    kl_weight: 1.0e-06
    perceptual_weight: 0.0
    disc_weight: 0.5
    disc_in_channels: 1
    disc_conditional: false
encoder_decoder_config:
  double_z: True
  z_channels: 4
  resolution: 256
  in_channels: 1
  out_ch: 1
  ch: 128
  ch_mult: [1,2,2,2]  # num_down = len(ch_mult)-1
  num_res_blocks: 2
  attn_resolutions: [64,32]
  dropout: 0.0