# Configuration for an LTX-Video autoencoder with a latent space of (B,256,4,1,1),
# which accepts input data of shape (B, 1, 25, 32, 32) in format (B,C,F,H,W)
vae_config:
  target: xdiffusion.autoencoders.ltx_vae.CausalVideoAutoencoder
  params:
    dims: 3
    in_channels: 1
    out_channels: 1
    latent_channels: 128
    blocks: [
        ["res_x", 4],
        ["compress_all", 1],
        ["res_x_y", 1],
        ["res_x", 3],
        ["compress_all", 1],
        ["res_x_y", 1],
        ["res_x", 3],
        ["compress_all", 1],
        ["res_x", 3],
        ["res_x", 4],
    ]
    scaling_factor: 1.0
    norm_layer: "pixel_norm"
    patch_size: 4
    latent_log_var: "uniform"
    use_quant_conv: False
    causal_decoder: False

    loss_config:
      target: xdiffusion.autoencoders.losses.LPIPSWithDiscriminator
      params:
        disc_start: 10000
        kl_weight: 1.0e-06
        perceptual_weight: 0.5
        disc_weight: 0.5
        disc_in_channels: 1
        disc_conditional: false
        use_3d: True
        use_reconstruction_gan: True
        wavelet_loss_weight: 0.5
        rec_loss: "l2"
        learned_logvar: False

# Describes the dataset used in training.
data:
  # Spatial width/height of the data input to the model.
  image_size: 64
  # Number of channels in the input data
  num_channels: 1
  # The number of classes in the dataset
  num_classes: 10
  # The number of frames in the input dataset. This could be different
  # than the number of frames that is in the data itself.
  input_number_of_frames: 25
  # Method of processing the input frames. Can be "clip", which takes
  # the first N frames, or "sample", which skips frames from the input
  # to get the required number of frames (so a source video of 30 frames, with input_number_of_frames
  # set to 15, would take every (30//15=2) frames).
  frame_processing: "clip"

# Describes training parameters, including sampling
# strategies for input data.
training:
  dataset: "video/moving_mnist"
  batch_size: 32
  gradient_accumulation_steps: 1
  mixed_precision: "bf16"