sampling:
  output_channels: 1
  output_spatial_size: 32
  target: xdiffusion.samplers.consistency.OneStepConsistencySampler
  params:
    sigma_min: 0.002
    sigma_max: 80
    rho: 7
    clip_denoised: True
